import { Injectable } from '@angular/core';
import { Product } from './Product';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  getProductsSmall() {
    const promisedData = new Promise<Product[]>((resolve) => {
      resolve([
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Bamboo Watch',
          description: 'Product Description',
          image: 'men clothes 2.jpeg',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'men clothes',
          description: 'Product Description',
          image: 'men clothes.webp',
          price: 66,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'women soins de beauté',
          description: 'Product Description',
          image: 'women soins de beauté.jpg',
          price: 67,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'women clothes',
          description: 'Product Description',
          image: 'women clothes.jpg',
          price: 68,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Bamboo Watch',
          description: 'Product Description',
          image: 'women clothes underware.webp',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Bamboo Watch',
          description: 'Product Description',
          image: 'women flower clothes.jpeg',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Bamboo Watch',
          description: 'Product Description',
          image: 'men clothes 2.jpeg',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'men clothes',
          description: 'Product Description',
          image: 'men clothes.webp',
          price: 66,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'women towels',
          description: 'Product Description',
          image: 'women towels.jpeg',
          price: 67,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'women clothes 2',
          description: 'Product Description',
          image: 'women clothes 2.jpg',
          price: 68,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Bamboo Watch',
          description: 'Product Description',
          image: 'women clothes underware.webp',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
        {
          id: '1000',
          code: 'f230fh0g3',
          name: 'Women trico winter',
          description: 'Product Description',
          image: 'Women trico winter.jpg',
          price: 65,
          category: 'Accessories',
          quantity: 24,
          inventoryStatus: 'INSTOCK',
          rating: 5,
        },
      ]);
    });
    return promisedData;
  }
}
